micronaut:
  application:
    name: pixKeyManager
    http:
      client:
        logger-name: logger
      services:
        otherClient:
          logger-name: other.client

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pix-keymanager-grpc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  contas:
    url: ${ITAU_CONTAS_URL:`http://localhost:9091/`}

bcb:
  pix:
    url: ${BCB_PIX_URL:`http://localhost:8082/`}
